language: generic

dist: bionic

sudo: required

services:
  - docker

notifications:
  email: false

env:
  - OTP_VERSION=22.0

cache:
  directories:
    - /home/travis/cache/docker-otp-22.0
    - test/cavp_SUITE_data/186-3rsatestvectors
    - test/cavp_SUITE_data/archive
    - test/cavp_SUITE_data/pkcs-1v2-1-vec

before_install:
  - rm -rf ./docker-otp-${OTP_VERSION}
  - mkdir -p /home/travis/cache/docker-otp-${OTP_VERSION}
  - ln -svf /home/travis/cache/docker-otp-${OTP_VERSION} ./docker-otp-${OTP_VERSION}
  - make docker-setup DOCKER_OTP_VERSION=${OTP_VERSION}

script:
  - make docker-test DOCKER_OTP_VERSION=${OTP_VERSION}
